services:
  database:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: solvro_backend
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/database:/var/lib/postgres/data
